# Default values for tile-server https://github.com/maptiler/tileserver-gl
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# https://cadastre.data.gouv.fr/datasets/cadastre-etalab

initContainerDownload:
  enabled: true
  image: inseefrlab/onyxia-base
  securityContext: {}
  s3:
    accessKey: tile-server
    secretKey: tile-server
    sessionToken: 
    bucket: tile-server
    endpoint: todo
    insecure : true
  mbtiles:
    file: maptiler-osm-2020-02-10-v3.11-france_nantes.mbtiles

replicaCount: 1

image:
  repository: maptiler/tileserver-gl
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  # fsGroup: 2000

securityContext:
  runAsNonRoot: false
  runAsUser: 0
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx-public"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: tile-server.url
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
      - tile-server.url


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
